<?php

// Load newsmanager.views.inc from the newsmanager module
module_load_include('inc', 'newsmanager', 'newsmanager.views');

/**
 * Implements hook_menu()
 */
function newsmanager_menu() {
	// Create administration page for Newsmanager-Module
	// with an entry in the config page.
	$items['admin/config/newsmanager'] = array(
		'title' => t('Newsmanager'),
		'description' => t('Configure Newsmanager'),
		'position' => 'right',
    'weight' => -15,
		'page callback' => 'system_admin_menu_block_page',
		'access arguments' => array('administer newsmanager'),
		'file' => 'system.admin.inc',
		'file path' => drupal_get_path('module', 'system'),
	);
	$items['admin/config/newsmanager/settings'] = array(
		'title' => t('Author and Date settings'),
		'description' => t('Configure wheter date and author are showed or not.'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array('newsmanager_admin_settings'),
		'access arguments' => array('administer newsmanager'),
		'file' => 'newsmanager.admin.inc',
	);
	
	return $items;
}

/**
 * Implements hook_permission()
 */
function newsmanager_permission() {
	// Create permission for administration page of Newsmanager-Module
	$permissions['administer newsmanager'] = array(
		'title' => t('Administer Newsmanager'),
		'description' => t('Users with this permission are allowed to administer the Newsmanager.'),
	);
	
	return $permissions;
}