<?php

/**
 * @file
 * Module file for Newsmanager Module.
 * @author indelicato sven
 */
// Load newsmanager.views.inc from the newsmanager module
module_load_include('inc', 'newsmanager', 'newsmanager.views');

/**
 * Implements hook_menu()
 */
function newsmanager_menu() {
	// Create administration page for Newsmanager-Module
	// with an entry in the config page.
	$items['admin/config/newsmanager'] = array(
		'title' => 'Newsmanager',
		'description' => 'Configure Newsmanager',
		'position' => 'right',
    'weight' => -15,
		'page callback' => 'system_admin_menu_block_page',
		'access arguments' => array('administer newsmanager'),
		'file' => 'system.admin.inc',
		'file path' => drupal_get_path('module', 'system'),
	);
	$items['admin/config/newsmanager/settings'] = array(
		'title' => 'Author and Date settings',
		'description' => 'Configure whether date and author are shown or not.',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('newsmanager_admin_settings'),
		'access arguments' => array('administer newsmanager'),
		'file' => 'newsmanager.admin.inc',
	);
	
	return $items;
}

/**
 * Implements hook_permission()
 */
function newsmanager_permission() {
	// Create permission for administration page of Newsmanager-Module
	$permissions['administer newsmanager'] = array(
		'title' => t('Administer Newsmanager'),
		'description' => t('Users with this permission are allowed to administer the Newsmanager.'),
	);
	
	return $permissions;
}

/**
 * Implements hook_theme_registry_alter()
 */
function newsmanager_theme_registry_alter(&$theme_registry) {
	$mod_path = drupal_get_path('module', 'newsmanager');
	$theme_registry_copy = $theme_registry;
	_theme_process_registry($theme_registry_copy, 'phptemplate', 'theme_engine', 'pow', $mod_path);
	$theme_registry += array_diff_key($theme_registry_copy, $theme_registry);
	$hooks = array('node');
	foreach ($hooks as $h) {
		_newsmanager_insert_after_first_element($theme_registry[$h]['theme paths'], $mod_path);
	}
}

/**
 * Helper function for re-ordering arrays (needed by theme_registry_alter)
 */
function _newsmanager_insert_after_first_element(&$a, $element) {
	if(is_array($a)) {
		$first_element = array_shift($a);
		array_unshift($a, $first_element, $element);
	}
}